### ISSUE TITLE
Support reading configuration from pyproject.toml

### ISSUE THREAD

**Issue by Tatsh** [newrelic/newrelic-python-agent#1229]
### Is your feature request related to a problem? Please describe.
No.

### Feature Description
Please read configuration from the shared configuration file `pyproject.toml` as well as `newrelic.ini` (one or the other, preferring `pyproject.toml`). Example mapping based on current `newrelic.ini` format:

```toml
[tool.newrelic]
log_level = "info"
high_security = false
monitor_mode = true
app_name = "app_name"

# Extends above
[tool.newrelic.production]
app_name = "app_name (Production)"

# [import-hook:django]
# instrumentation.scripts.django_admin = process_tasks runjob runjobs
# becomes:

[tool.newrelic.import-hook.django.instrumentation.scripts] # replace : with -
django_admin = ["process_tasks", "runjob", "runjobs"]
```

This will help to reduce the amount of project metadata files needed.

### Describe Alternatives
n/a

### Additional context

[PEP 621 – Storing project metadata in pyproject.toml](https://peps.python.org/pep-0621/)

### Priority
Really Want.
