### ISSUE TITLE
Fast API Websocket coroutines throw attribute error when run with newrelic admin

### ISSUE THREAD

**Issue by sankarpa** [newrelic/newrelic-python-agent#742]
**Description**
  I am using newrelic agent 8.5.0 with my fastapi which houses both rest and websocket apis. The app get deployed in kubernetes and here is how the container command looks like 

```
   containers:
        - name: a-service
          image: 'a-service:latest'
          command:
            - newrelic-admin
            - run-program
            - uvicorn
            - app.main:app
            - --port=8000
            - --host=0.0.0.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
              protocol: TCP
```
         

The container comes up healthy and runs , but the coroutines throws error with attribute not found error when calling async functions.  The same is working fine when i run the container without newrelic-admin
